#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║  📤 PUSH CODE TO GITHUB                                                    ║"
echo "╠════════════════════════════════════════════════════════════════════════════╣"
echo "║                                                                            ║"
echo "║  Your code is committed locally and ready to push!                         ║"
echo "║  Repository: git@github.com:sushanth26/T-Bot.git                           ║"
echo "║                                                                            ║"
echo "╠════════════════════════════════════════════════════════════════════════════╣"
echo "║  🔑 SETUP GITHUB ACCESS (Choose one option):                               ║"
echo "║                                                                            ║"
echo "║  OPTION 1: Use GitHub CLI (Easiest)                                        ║"
echo "║  ────────────────────────────────────                                     ║"
echo "║  gh auth login                                                             ║"
echo "║  git push -u origin main                                                   ║"
echo "║                                                                            ║"
echo "║  OPTION 2: Create SSH Key                                                  ║"
echo "║  ─────────────────────────                                                ║"
echo "║  ssh-keygen -t ed25519 -C \"your_email@example.com\"                        ║"
echo "║  cat ~/.ssh/id_ed25519.pub                                                 ║"
echo "║  # Copy the output                                                         ║"
echo "║  # Go to GitHub.com → Settings → SSH Keys → New SSH key                   ║"
echo "║  # Paste and save                                                          ║"
echo "║  git push -u origin main                                                   ║"
echo "║                                                                            ║"
echo "║  OPTION 3: Use Personal Access Token (HTTPS)                               ║"
echo "║  ───────────────────────────────────────────                              ║"
echo "║  # Get token from GitHub.com → Settings → Developer Settings → Tokens     ║"
echo "║  git remote set-url origin https://github.com/sushanth26/T-Bot.git         ║"
echo "║  git push -u origin main                                                   ║"
echo "║  # Enter username: sushanth26                                              ║"
echo "║  # Enter password: [paste your token]                                      ║"
echo "║                                                                            ║"
echo "╠════════════════════════════════════════════════════════════════════════════╣"
echo "║  📊 WHAT'S BEING PUSHED:                                                   ║"
echo "║                                                                            ║"
echo "║  ✅ Backend (Modular Python/FastAPI)                                       ║"
echo "║     • config/ - Settings and API keys config                               ║"
echo "║     • services/ - EMA, News, Crossover, Premarket services                 ║"
echo "║     • api/ - Route handlers                                                ║"
echo "║     • server.py - Main entry point                                         ║"
echo "║                                                                            ║"
echo "║  ✅ Frontend (React TypeScript)                                            ║"
echo "║     • 3-column layout                                                      ║"
echo "║     • Color-coded EMA list                                                 ║"
echo "║     • Search with autocomplete                                             ║"
echo "║     • Loading skeletons                                                    ║"
echo "║     • Live data updates                                                    ║"
echo "║                                                                            ║"
echo "║  ✅ Documentation                                                          ║"
echo "║     • README.md                                                            ║"
echo "║     • STRUCTURE.md                                                         ║"
echo "║     • Setup scripts                                                        ║"
echo "║                                                                            ║"
echo "║  🔒 EXCLUDED (via .gitignore):                                             ║"
echo "║     • venv/ (Python dependencies)                                          ║"
echo "║     • node_modules/ (Node dependencies)                                    ║"
echo "║     • .env (API keys - SECURE!)                                            ║"
echo "║                                                                            ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📝 Files committed: 44 files, 8671 lines"
echo "🔄 Ready to push to: https://github.com/sushanth26/T-Bot"
echo ""
echo "Choose an option above to authenticate and push!"

